# User config
author: "Emily Hong"
tagline: "An Exploration of Identity"
description: "A collection of identities and stories of individuals in the Asian American community presented through illustrations and interviews."
keywords: "Asian American, Asian, American, America, Identity, Harvard, Interview"

# Site config
baseurl: "/identityexploration/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
