# User config
author: "Emily Hong"
tagline: "An Exploration of Identity"
description: "A collection of identities and stories of individuals in the Asian American community presented through illustrations and interviews."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/identityexploration"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
