# User config
author: "Emily Hong"
tagline: "An Exploration of Identity"
description: "interviews from the Asian American community at Harvard"
keywords: "Asian American, Asian, American, America, Identity, Harvard, Interview"

# Site config
baseurl: "/identityexploration/"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

google_analytics: UA-125086399-1
